using UnityEngine;

namespace Simulation
{
    /// <summary>
    /// Instantiate Objects
    /// </summary>
    public class GenerationManager : SingletonMonoBehaviour<GenerationManager>
    {
        [Tooltip("Parent of battle objects generated by this")]
        [SerializeField]
        private Transform _parentBattleObjects;

        /// <summary>
        /// Parent of battle objects generated by this
        /// </summary>
        public Transform parentBattleObjects
        {
            get { return _parentBattleObjects; }
        }

        /// <summary>
        /// Instantiate a GameObject
        /// </summary>
        public virtual GameObject GenerateObject(
            GameObject gameObject,
            Vector3 position,
            Quaternion rotation,
            Transform parent
        )
        {
            GameObject newObject = Instantiate(gameObject, parent);
            newObject.transform.position = position;
            newObject.transform.rotation = rotation;

            return newObject;
        }
    }
}
